---
title: "Sparklyr Demo: R Interface with Apache Spark"
author: "Klaus Miller, Goethe University Frankfurt"
date: "May 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Example: Cluster Analysis
Using Spark.ML to predict cluster membership with the iris dataset

Slightly adapted from source: https://spark.rstudio.com/


Load Packages

```{r message=FALSE, warning=FALSE, paged.print=FALSE}

library(tidyverse)

```



Installation

```{r message=FALSE, warning=FALSE, paged.print=FALSE}

#install.packages("sparklyr")

# Upgrade to latest version
#devtools::install_github("rstudio/sparklyr")

```
Connecting to Spark

```{r warning=FALSE, paged.print=FALSE}

library(sparklyr)
sc <- spark_connect(master = "local")

```

Copy data from R into Spark Cluster

```{r}

iris_tbl <- copy_to(sc, iris, "iris", overwrite = TRUE)
iris_tbl

```

Inspect Data Set

```{r}

glimpse(iris_tbl)

```

Simple Filtering Example Using Dplyr

```{r}

iris_tbl %>% filter(Sepal_Length < 5.0)

```

Use Spark K-Means Clustering

```{r}

kmeans_model <- iris_tbl %>%
  select(Petal_Width, Petal_Length) %>%
  ml_kmeans(formula= ~ Petal_Width + Petal_Length, k = 3)

# print our model fit
kmeans_model

```
```{r}
# predict the associated class
predicted <- ml_predict(kmeans_model, iris_tbl) %>%
  collect

table(predicted$Species, predicted$prediction)
```


```{r}
# plot cluster membership
ml_predict(kmeans_model) %>%
  collect() %>%
  ggplot(aes(Petal_Length, Petal_Width)) +
  geom_point(aes(Petal_Width, Petal_Length, col = factor(prediction + 1)),
             size = 2, alpha = 0.5) + 
  geom_point(data = kmeans_model$centers, aes(Petal_Width, Petal_Length),
             col = scales::muted(c("red", "green", "blue")),
             pch = 'x', size = 12) +
  scale_color_discrete(name = "Predicted Cluster",
                       labels = paste("Cluster", 1:3)) +
  labs(
    x = "Petal Length",
    y = "Petal Width",
    title = "K-Means Clustering",
    subtitle = "Use Spark.ML to predict cluster membership with the iris dataset."
  )
```

